# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('sourceURL', models.CharField(max_length=255)),
                ('picURL', models.CharField(max_length=255)),
                ('originURL', models.CharField(max_length=255)),
                ('accessNum', models.IntegerField()),
                ('academicCode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.Academic')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('ip', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('academicCode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.Academic')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.News')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('sourceURL', models.CharField(max_length=255)),
                ('originURL', models.CharField(max_length=255)),
                ('accessNum', models.IntegerField()),
                ('academicCode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.Academic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('studentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('lastModified', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='newscomment',
            name='studentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.StudentInfo'),
        ),
    ]
