# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SCU', max_length=255)),
                ('address', models.CharField(default='www.scu.edu.cn', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('sourceURL', models.CharField(max_length=255)),
                ('picURL_Path', models.CharField(max_length=255)),
                ('originURL', models.CharField(max_length=255)),
                ('accessNum', models.IntegerField(default=0)),
                ('academy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.Academy')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.News')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('sourceURL', models.CharField(max_length=255)),
                ('originURL', models.CharField(max_length=255)),
                ('accessNum', models.IntegerField(default=0)),
                ('academy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.Academy')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('studentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(default='', max_length=255)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='newscomment',
            name='studentInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.StudentInfo'),
        ),
    ]
