# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
        migrations.AlterField(
            model_name='news',
            name='academy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notice',
            name='academy',
            field=models.CharField(max_length=255),
        ),
    ]
