# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='academicCode',
            new_name='academic',
        ),
        migrations.RenameField(
            model_name='newscomment',
            old_name='academicCode',
            new_name='academic',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='academicCode',
            new_name='academic',
        ),
    ]
