# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0002_auto_20161106_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='picURL',
        ),
        migrations.AddField(
            model_name='news',
            name='picURL_Path',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='academic',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='academic',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='accessNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='originURL',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='sourceURL',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='ip',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='time',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='notice',
            name='accessNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notice',
            name='originURL',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sourceURL',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='lastModified',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='nickname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
