# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0003_auto_20161106_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='academic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspush.Academic'),
        ),
        migrations.AlterField(
            model_name='news',
            name='originURL',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='picURL_Path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='sourceURL',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspush.Academic'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='ip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspush.News'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspush.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspush.Academic'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='originURL',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sourceURL',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='lastModified',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
