# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0004_auto_20161106_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
