# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0005_auto_20161106_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='academic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.Academic'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.News'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
