# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0006_auto_20161106_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomment',
            name='academic',
        ),
    ]
