# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0007_remove_newscomment_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='studentID',
            field=models.ForeignKey(default='0000000000000', on_delete=django.db.models.deletion.CASCADE, to='newspush.StudentInfo'),
        ),
    ]
