# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0008_auto_20161106_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomment',
            name='studentID',
        ),
        migrations.AddField(
            model_name='newscomment',
            name='studentInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.StudentInfo'),
        ),
    ]
