# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspush', '0009_auto_20161106_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic',
            new_name='Academy',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='academic',
            new_name='academy',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='academic',
        ),
        migrations.AddField(
            model_name='notice',
            name='academy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newspush.Academy'),
        ),
    ]
